language: java
sudo: required
jdk:
- oraclejdk8
env:
  matrix:
    - ENGINE=lucee@4.5
    - ENGINE=lucee@5-SNAPSHOT
    - ENGINE=adobe@2016
    - ENGINE=adobe@11
    - ENGINE=adobe@10
before_install:
- mkdir /tmp/bin
- export PATH=$PATH:/tmp/bin
install:
- curl --location 'https://www.ortussolutions.com/parent/download/commandbox/type/deb' -o /tmp/commandbox.deb
- sudo dpkg -i /tmp/commandbox.deb
- box install
before_script:
- box server start cfengine=$ENGINE
script: >
  testResults="$(box testbox run runner='http://127.0.0.1:12121/tests/runner.cfm' )";
  echo "$testResults";
  if grep -i "\[(Failures|Errors): [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi
notifications:
    email: false