language: java
sudo: false
jdk:
- oraclejdk8
env:
  matrix:
    - PLATFORM=lucee@4.5
    - PLATFORM=lucee@5-SNAPSHOT
    - PLATFORM=adobe@2016
    - PLATFORM=adobe@11
    - PLATFORM=adobe@10
before_install:
- mkdir /tmp/bin
- export PATH=$PATH:/tmp/bin
install:
- curl --location 'http://integration.stg.ortussolutions.com/artifacts/ortussolutions/commandbox/3.1.0/commandbox-bin-3.1.0.zip' -o /tmp/box.zip
- unzip /tmp/box.zip -d /tmp/bin
- /tmp/bin/box install
before_script:
- box server start cfengine=$PLATFORM
script: >
  testResults="$(box testbox run runner='http://127.0.0.1:7777/tests/runner.cfm' )";
  echo "$testResults";
  if grep -i "\[(Failures|Errors): [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi
notifications:
    email: false